version: "3"

networks:
  mdr:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./registry:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached"
    depends_on:
      - registry
    networks:
      - mdr

  registry:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: registry
    volumes:
      - "./registry:/var/www/html"
    networks:
      - mdr

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: registry
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mdr