version: "3"

networks:
  mdr:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "8080:80"
    volumes:
      - "./registry:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - registry
    networks:
      - mdr
    
  registry:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: registry
    volumes:
      - "./registry:/var/www/html"
    networks:
      - mdr